version: "3.9"

services:
  db:
    image: mysql:8.0.28
    ports:
      - "6606:3306"
    environment: 
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=test
    # - MYSQL_ROOT_PASSWORD=root