version: "3.9"

services:
  db:
    image: mysql:8.0.28
    ports:
      - "6606:3306"
    platform: linux/amd64
    environment: 
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=test
    # - MYSQL_ROOT_PASSWORD=root

  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.python
      args:
        - REQUIREMENTS=requirements.txt
    links:
      - db:db
    volumes:
      - .:/var/mysql_data_generator/
    working_dir: /var/mysql_data_generator/generator/
    # keep app container running
    command: "sh -c 'tail -f /dev/null'"
